name = "hicm-hub"
compatibility_date = "2026-07-13"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "hicm-hub-db"
database_id = "bc9a2b59-e792-4eb4-8ce5-6ef3b348f945"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "hicm-hub-uploads"
